spring:
  application:
    name: learning-spring-ai
  datasource:
    url: jdbc:postgresql://localhost:5433/spring_ai_vector_embedding
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        options:
#          model: nate/instinct
    vectorstore:
      pgvector:
        index-type: HNSW
        dimension: 1536
        initialize-schema: true
    openai:
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.9
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            table-name: chat_memory




logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG